### PR TITLE
Note case sentivity in help

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by gliptak** [comment]
Anything else needed before this can be committed? Thanks

**Comment by oleg-nenashev** [comment]
It would make sense to replace "authentication backend" to "security realm" just to reference common Jenkins terms. You could also add a hyperlink to https://wiki.jenkins-ci.org/display/JENKINS/Securing+Jenkins in order to clarify it

**Comment by daniel-beck** [comment]
I don't think this is correct. Is there a security realm this does not apply to?

**Comment by gliptak** [comment]
@oleg-nenashev Updated text per your comments
@daniel-beck I'm not sure if it does or doesn't apply to all, but the mention of "case sensitivity" likely will help some others out

**Comment by jglick** [comment]
Is this still applicable given #9?

**Comment by gliptak** [comment]
I would like to deploy an updated plugin and check ...

**Pull request closed without merging**
