### PR TITLE
Compatibility with jenkins-buttons (2.378+)

### PR DESCRIPTION
**Pull request by NotMyFault**
Adopts https://github.com/jenkinsci/jenkins/pull/7364

### CODE REVIEW

**Comment by daniel-beck** [comment]
These classes aren't new though, right? So anyone on older Jenkins releases, including current and upcoming LTS, will have inconsistent admin monitor presentations?

**Comment by NotMyFault** [comment]
Jenkins buttons exist for quite a while yet, although there's no coherent logic for a dismiss component yet, just a draft PR for core. Plugin authors used to handle the things on their own previously.

**Comment by daniel-beck** [comment]
Right, but before your PR, Jenkins core admin monitors did not use the destructive buttons. So it's not "forward compatibility" as in the HTML tooltip PR compatibility PRs, but rather as in Jenkins core 2.378+ behavior, regardless of the version of Jenkins this plugin is installed on. Or what am I missing?

**Comment by NotMyFault** [comment]
>  that result in the expected behavior on any core version, but rather as in Jenkins core 2.378+ behavior,

You are correct. Jenkins versions starting with the introduction of this jenkins-button component ranging to 2.378 would display things differently, if you merge this PR.

**Comment by NotMyFault** [comment]
Closing, because the core PR is about to get reverted.

**Pull request closed without merging**
