### PR TITLE
Better assertion in `InheritanceMigrationTest`

### PR DESCRIPTION
**Pull request by jglick**
Helpful in https://github.com/jenkinsci/cloudbees-folder-plugin/pull/375.

### CODE REVIEW

**Review by julieheard — APPROVED** [review]

**Comment by jglick** [comment]
@daniel-beck it could wait.

**Comment by jglick** [comment]
@daniel-beck is there some reason to hold this?

**Comment by daniel-beck** [comment]
I forgot about it when I released 3.2.2, and I generally try not to create releases without production code changes. I can merge this, if you prefer that to it being open?

**Comment by jglick** [comment]
> I can merge this, if you prefer that to it being open?

Yes please. There is no need to trigger a release but I prefer to have my PRs merged as soon as they pass automated checks and review.

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
