### PR TITLE
[JEP-295] Avoid explicit references to AccessDeniedException in tests

### PR DESCRIPTION
**Pull request by jglick**
For PCT compatibility with https://github.com/jenkinsci/jenkins/pull/4848.

### CODE REVIEW

**Review by Wadeck — APPROVED** [review]
Not tested but it's what we talked about to prevent compatibility issue

**Comment by jglick** [comment]
Looks like @daniel-beck is the sole maintainer.

**Comment by jglick** [comment]
Trying to trigger Incrementals deployment…

**Comment by daniel-beck** [comment]
JEP-227 actually 😭

**Pull request merged**
