### PR TITLE
[JENKINS-49199] added @DataBoundConstructor

### PR DESCRIPTION
**Pull request by daspilker**
[JENKINS-49199](https://issues.jenkins-ci.org/browse/JENKINS-49199)

### CODE REVIEW

**Comment by gliptak** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-49199

@daniel-beck Please trigger another build of this PR. Thanks

**Comment by daniel-beck** [comment]
@gliptak Thanks for the reminder, looks like the infra magically recovered from the previous brokenness.

@daspilker Could you walk me through this implementation? Does it need to be `@DataBoundConstructor`? Can it be `@Restricted`?

**Comment by daspilker** [comment]
@daniel-beck Yes, it needs to be a `@DataBoundConstructor` for the structs-plugin magic. It can be `@DoNotUse` or `NoExternalUse` since access will only be through reflection.

**Comment by gliptak** [comment]
@daspilker Are you still looking to improve this PR?

**Comment by daspilker** [comment]
@daniel-beck added `NoExternalUse`, rebased to master and verified that the PR still fixes the issue.

**Comment by daniel-beck** [comment]
Subsumed in https://github.com/jenkinsci/matrix-auth-plugin/pull/45 with some further quality of life improvements (user-friendly permission names!)

**Comment by mwarkentin** [comment]
@daniel-beck did you mean to link to a different PR?

**Comment by daniel-beck** [comment]
@mwarkentin Yes, https://github.com/jenkinsci/matrix-auth-plugin/pull/48. Thanks for bringing this up.

**Pull request closed without merging**
