### PR TITLE
Add configuration-as-code support with extra contructor

### PR DESCRIPTION
**Pull request by MadsNielsen**
We do not need to do major work to support c-as-c. Adding an extra constructor enables this.

### CODE REVIEW

**Comment by daniel-beck** [comment]
This needs better justification. Is it because the map has no setter?

Also, needs Javadoc and `@since TODO`.

**Comment by MadsNielsen** [comment]
@daniel-beck Yep, i need to set the `grantedPermissions` map. I'm open to suggestions on how to do it otherwise. I can easilly add the javadoc etc.

**Comment by MadsNielsen** [comment]
@daniel-beck And i could probably do the same using reflection in configuration-as-code plugin but having a simple constructor to generate the Authentication section option seemed to be a better solution.

**Comment by daniel-beck** [comment]
@MadsNielsen Not opposed, just the reason wasn't clear, and no explanation given.

**Comment by MadsNielsen** [comment]
@daniel-beck Just awright, i actually did forget to add a justification on the commit. So i've updated my pull request with a bit of JavaDoc and some `@since`'s to be filled out.

**Comment by daniel-beck** [comment]
@MadsNielsen How does this relate to https://github.com/jenkinsci/matrix-auth-plugin/pull/45? Is the other also relevant for you?

**Comment by MadsNielsen** [comment]
@daniel-beck It's probably a better solution than the one i proposed, but yes, essentially we're trying to solve the same problem. I did not know that the form you submit could be condensed to a simple list of strings, as you have a group name for each set of granted permissions.

**Comment by daniel-beck** [comment]
Making this nicer in https://github.com/jenkinsci/matrix-auth-plugin/pull/46

**Pull request closed without merging**
