### PR TITLE
Migrate into localization-zh-cn-plugin

### PR DESCRIPTION
**Pull request by LinuxSuRen**
See https://github.com/jenkinsci/localization-zh-cn-plugin

### CODE REVIEW

**Comment by jvz** [comment]
Build failed for some reason. Might want to do `git commit --amend && git push --force` to rebuild.

**Comment by jvz** [comment]
It's possible the build failure is unrelated then.

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers Anyone could take some time to help me review this pr? Thanks.

**Comment by daniel-beck** [comment]
I would rather not migrate further translations into the standalone plugin while significant technical limitations (https://github.com/daniel-beck/localization-support-plugin/issues/1) are unresolved.

**Pull request closed without merging**
