### PR TITLE
use new dialog to prompt for user/group

### PR DESCRIPTION
**Pull request by mawinter69**
replaces the browser built-in prompt and alert calls with the dialogs for better theming.

image
image
image
image

### Testing done
Manual testing

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]
Works great, thanks!

**Comment by daniel-beck** [comment]
@mawinter69 How eager are you to see a release with this change?

**Comment by mawinter69** [comment]
As this is just nice to have it is not urgent from my point of view.

**Comment by basil** [comment]
Either this or #152 causes https://github.com/jenkinsci/acceptance-test-harness/issues/1803.

**Comment by basil** [comment]
On further inspection, https://github.com/jenkinsci/acceptance-test-harness/issues/1803 is caused by this PR, not #152.

**Pull request merged**
