### PR TITLE
[JENKINS-34616] Add symbols, getter, and constructor for pipeline

### PR DESCRIPTION
**Pull request by daniel-beck**
Supersedes https://github.com/jenkinsci/matrix-auth-plugin/pull/14

[JENKINS-34616](https://issues.jenkins-ci.org/browse/JENKINS-34616)

- ~~I don't like the fully qualified permission IDs – ideally, they would be shortened to "Class.Field" if unambiguous.~~ (JENKINS-17200)
- ~~Needs usage docs~~ Optional, sort of, snippet gen works after all.
- [x] Needs autotests, manual testing etc.

----

Snippet generator:

> screen shot

Result (formatted for readability):

```groovy
properties([
    authorizationMatrix(
        inheritanceStrategy: nonInheriting(), 
        permissions: [
            'hudson.model.Item.Read:authenticated', 
            'hudson.model.Run.Delete:danielbeck', 
            'hudson.model.Item.Build:danielbeck', 
            'hudson.model.Item.Configure:danielbeck']
            ),
    pipelineTriggers([])])
```

@jenkinsci/code-reviewers assemble!

### CODE REVIEW

**Comment by daniel-beck** [comment]
> I don't like the fully qualified permission IDs – ideally, they would be shortened to "Class.Field" if unambiguous.

Doesn't work with `SCM.Tag`, as `Permission#getAll()` doesn't include it (likely [JENKINS-17200](https://issues.jenkins-ci.org/browse/JENKINS-17200)). So this would be too brittle right now to support it, but could always be added later.

**Comment by jglick** [comment]
I see no problem with the current format. Better to avoid ambiguity.

BTW `pipelineTriggers([])` is removed by https://github.com/jenkinsci/workflow-job-plugin/pull/42 which is waiting for a fix to https://github.com/jenkinsci/workflow-job-plugin/pull/41.

**Comment by daniel-beck** [comment]
Not sure how to implement the restriction of eligible permissions here. I suppose I'll wait for https://github.com/jenkinsci/matrix-auth-plugin/pull/33 first to not introduce a greater mess. Filed [JENKINS-46944](https://issues.jenkins-ci.org/browse/JENKINS-46944)

**Comment by daniel-beck** [comment]
I'm not super happy with the system wide logging without providing a very useful context for this. Don't have a much better idea right now.

**Pull request merged**
