### PR TITLE
prototype js removal code changes

### PR DESCRIPTION
**Pull request by rsahoo7495**
changed YAHOO.lang.escapeHTML() method to javascript method in js file https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/resources/hudson/security/table.js
### Testing done
mvn verify and mvn clean install got success
After changes and build, added plugin hpi to jenkins instance

image

provided global access to the user for read

image

provided project level access for build and read

image

Now we can have access to in the project for build

image

Debugging in browser with code, it still works well with new code

image

image

image

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
Interesting approach to sanitize the string with the text node. I did it with basic escaping in [#152](https://github.com/jenkinsci/matrix-auth-plugin/pull/152/commits/16fb197cf5b9b879ede52b82e9e15355baa0a12b#diff-c6b2a5410964a2ef01459a94e3469b313dcfb67b62dd32a222ac5715829ab9efR3-R5), but this seems more elegant.

The testing done is unconvincing, it does not actually invoke the code in a manner demonstrating that escaping is still being done correctly.

**Comment by rsahoo7495** [comment]
@daniel-beck thanks for your comment, escaping which u did in in [#152](https://github.com/jenkinsci/matrix-auth-plugin/pull/152/commits/16fb197cf5b9b879ede52b82e9e15355baa0a12b#diff-c6b2a5410964a2ef01459a94e3469b313dcfb67b62dd32a222ac5715829ab9efR3-R5) looks more convenient to me

**Comment by rsahoo7495** [comment]
did testing with input <>"'&Raj and added debugging screenshot

**Review by julieheard — APPROVED** [review]

**Comment by daniel-beck** [comment]
In that case I'll close this PR as it doesn't offer anything over the cleanup in #152. Note that I removed Prototype in #140, this just removes uses of YUI. The plugin is compatible with Jenkins 2.426+ already.

**Pull request closed without merging**
